name: Steam Hour Farmer

on:
  workflow_dispatch:

jobs:
  run-farmer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Farmer
        run: |
          export ACCOUNT_NAME="${{ secrets.ACCOUNT_NAME }}"
          export PASSWORD="${{ secrets.PASSWORD }}"
          export GAMES="${{ secrets.GAMES }}"
          node index.js
