name: Steam Hour Farmer (ASF)

on:
  workflow_dispatch:
    inputs:
      steam_guard:
        description: 'Сюда пиши код Steam Guard'
        required: false
        default: ''

jobs:
  run-asf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup ASF
        env:
          STEAM_LOGIN: ${{ secrets.ACCOUNT_NAME }}
          STEAM_PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          mkdir asf && cd asf
          wget https://github.com
          unzip ASF-linux-x64.zip
          chmod +x ArchiSteamFarm
          
          # Безопасно создаем конфиг без подстановки багнутых символов напрямую
          echo "{\"SteamLogin\": \"$STEAM_LOGIN\", \"SteamPassword\": \"$STEAM_PASSWORD\", \"Enabled\": true, \"GamesPlayed\": [730,521890,242760,1321680,620,268910,3257000,286690,570,578080]}" > config/bot.json

      - name: Run ASF
        run: |
          cd asf
          if [ ! -z "${{ github.event.inputs.steam_guard }}" ]; then
            ./ArchiSteamFarm --input "input bot 2FA ${{ github.event.inputs.steam_guard }}"
          else
            ./ArchiSteamFarm
          fi
